UPT/Core/FileHook.py: Add the dir_fd parameter to _hookrmdir
As of Python 3.3, os.rmdir takes an optional parameter dir_fd.
Add it to _hookrmdir to avoid the following error when running pytest:

>   os.rmdir(path, dir_fd=dir_fd)
E   TypeError: _hookrmdir() got an unexpected keyword argument 'dir_fd'

Signed-off-by: Rebecca Cran <rebecca@bsdio.com>